In [1]:
import numpy as np
import pandas as pd
import csv
import pickle

In [2]:
bfile = "data/GSE66499_series_matrix.txt"

bmat_raw = open(bfile, "r").read()
bmat_list = bmat_raw.split("!")

In [3]:
nfile = "data/GSE80796_series_matrix.txt"

nmat_raw = open(nfile, "r").read()
nmat_list = nmat_raw.split("!")

# Matrix Parsing

## Bronchial RNA

In [10]:
bmat_geoids = np.array(bmat_list[20].split("\t")[-1].replace('"', '').split(" ")[:-1])
bmat_geoids[:5]

array(['GSM1623452', 'GSM1623453', 'GSM1623454', 'GSM1623455',
       'GSM1623456'], dtype='<U10')

In [11]:
bmat_cancer = np.array([
    1 if s.split(" ")[-1] == "Y" else 0 
    for s in bmat_list[46].replace('"', '').replace('\n', '').split("\t")[1:]
])
bmat_cancer[:5]

array([0, 0, 1, 1, 1])

In [12]:
matrix_data = bmat_list[70].split("\n")[2:-1]

n_geoid = len(bmat_geoids)
n_rna = len(matrix_data)

In [13]:
probe_names = []
series_matrix = np.zeros((n_rna, n_geoid))
for r in range(n_rna):
    data_str = matrix_data[r]
    data_list = data_str.split("\t")
    
    probe = data_list[0].replace('"', '')
    samples = [float(s) for s in data_list[1:]]
    
    probe_names.append(probe)
    series_matrix[r] = samples

In [14]:
matrix_df = pd.DataFrame(series_matrix.T, index = bmat_geoids, columns = probe_names)
matrix_df.index.rename("geoid", inplace = True)
matrix_df.insert(0, "cancer", bmat_cancer)
matrix_df.to_csv("data/matrix_bronchial.csv", header = True, index = True)

matrix_df.head()

,cancer,7892501,7892502,7892503,7892504,7892505,7892506,7892507,7892508,7892509,...,8180409,8180410,8180411,8180412,8180413,8180414,8180415,8180416,8180417,8180418
geoid,,,,,,,,,,,,,,,,,,,,,
GSM1623452,0,4.216093,5.842999,4.980203,10.059506,5.019846,6.643097,6.017031,7.155189,10.788140,...,10.194038,10.516945,7.357735,8.375515,8.307193,10.754339,7.411120,6.186312,8.777097,9.784806
GSM1623453,0,4.477295,5.527915,5.125640,10.467440,5.182849,6.045693,6.547059,8.011207,10.814677,...,10.524005,10.533004,7.381779,8.307119,8.211558,10.586939,7.437256,6.320433,8.776844,9.862342
GSM1623454,1,4.192968,5.609544,4.603893,10.565574,4.886351,5.849225,6.652074,8.215739,10.908662,...,10.353227,10.693120,7.223452,8.467328,8.398528,10.904259,7.763389,6.184391,9.064446,9.734410
GSM1623455,1,3.857432,5.239925,4.875725,10.213407,4.475636,5.498195,7.000071,7.021440,10.936842,...,10.227046,10.476882,7.238507,8.365352,8.294859,11.067606,7.176992,6.300595,8.884312,9.684322
GSM1623456,1,4.179410,4.913780,4.688398,10.426099,5.461521,5.458753,6.344151,6.901630,10.813660,...,10.198178,10.340738,7.295370,8.304812,8.318317,10.599784,7.251437,6.336659,8.934200,9.608108

## Nasal RNA

### Auxiliary

In [21]:
nmat_geoids = np.array(nmat_list[11].split("\t")[-1].replace('"', '').split(" ")[:-1])
nmat_geoids[:5]

array(['GSM2137106', 'GSM2137107', 'GSM2137108', 'GSM2137109',
       'GSM2137110'], dtype='<U10')

In [22]:
nmat_cancer = np.array([
    1 if s.split(": ")[-1] == "Lung Cancer" else 0 
    for s in nmat_list[36].replace('"', '').replace('\n', '').split("\t")[1:]
])
nmat_cancer[:5]

array([1, 1, 1, 0, 1])

In [23]:
nmat_age = np.array([
    float(s.split(": ")[-1]) for s in nmat_list[40].replace('"', '').replace('\n', '').split('\t')[1:]
])

nmat_gender = np.array([
    1 if s.split(": ")[-1] == "Male" else 0
    for s in nmat_list[41].replace('"', '').replace('\n', '').split('\t')[1:]
])

In [24]:
nmat_smoker = nmat_list[37].replace('"', '').replace('\n', '').split('\t')[1:]
for i, s in enumerate(nmat_smoker):
    sp = s.split(": ")[-1]
    if sp == "Current Smoker":
        nmat_smoker[i] = 1
    elif sp == "Former Smoker":
        nmat_smoker[i] = 0

In [25]:
nmat_smoking_quit = nmat_list[38].replace('"', '').replace('\n', '').split('\t')[1:]
for i, s in enumerate(nmat_smoking_quit):
    sp = s.split(": ")[-1]
    if sp == "<15y":
        nmat_smoking_quit[i] = 1
    elif sp == ">=15y":
        nmat_smoking_quit[i] = -1
    elif sp == "NA":
        nmat_smoking_quit[i] = 0

In [26]:
nmat_mass_size = nmat_list[39].replace('"', '').replace('\n', '').split('\t')[1:]
for i, s in enumerate(nmat_mass_size):
    sp = s.split(": ")[-1]
    if sp == ">=3cm":
        nmat_mass_size[i] = 1
    elif sp == "<3cm":
        nmat_mass_size[i] = -1
    elif sp == "Ill defined infiltrate":
        nmat_mass_size[i] = 0
    else:
        nmat_mass_size[i] = None

In [27]:
nmat_packyears = nmat_list[44].replace('"', '').replace('\n', '').split('\t')[1:]
for i, s in enumerate(nmat_packyears):
    sp = s.split(": ")[-1]
    if sp == "NA":
        nmat_packyears[i] = None
    else:
        nmat_packyears[i] = sp

In [63]:
aux_df = pd.DataFrame(np.array([nmat_cancer, nmat_age, nmat_gender,
                       nmat_smoker, nmat_smoking_quit, nmat_mass_size, nmat_packyears]).T,
                      index = nmat_geoids,
                      columns = ["cancer", "age", "gender", "smoker", "smoking_quit", "mass_size", "packyears"]
                     )
aux_df.index.rename("geoid", inplace = True)
aux_df.head()

           cancer      age gender smoker smoking_quit mass_size packyears
geoid
GSM2137106      1       51      0      1            1        -1        47
GSM2137107      1       69      0      0           -1         1        15
GSM2137108      1       58      0      0            1        -1        38
GSM2137109      0       49      1      1            1         1        70
GSM2137110      1  45.3123      0      1            1         1         6

In [76]:
aux_df = aux_df.dropna()

In [ ]:
aux_df[aux_df["cancer"] == 0].age.median()dd

In [60]:
pd.crosstab(aux_df.mass_size, aux_df.cancer)

cancer      0    1
mass_size
-1         99   96
 0         44   16
 1         43  186

In [77]:
186+298

484

### Matrix

In [46]:
matrix_data = nmat_list[69].split("\n")[2:-1]

n_geoid = len(nmat_geoids)
n_rna = len(matrix_data)

In [47]:
probe_names = []
series_matrix = np.zeros((n_rna, n_geoid))
for r in range(n_rna):
    data_str = matrix_data[r]
    data_list = data_str.split("\t")
    
    probe = data_list[0].replace('"', '')
    samples = [float(s) for s in data_list[1:]]
    
    probe_names.append(probe)
    series_matrix[r] = samples

In [48]:
matrix_df = pd.DataFrame(series_matrix.T, index = nmat_geoids, columns = probe_names)
matrix_df.index.rename("geoid", inplace = True)

matrix_df.head()

,7892501,7892502,7892503,7892504,7892505,7892506,7892507,7892508,7892509,7892510,...,8180408,8180409,8180410,8180411,8180413,8180414,8180415,8180416,8180417,8180418
geoid,,,,,,,,,,,,,,,,,,,,,
GSM2137106,2.288567,3.467242,3.106184,8.791999,4.012690,4.081984,5.291053,5.464147,8.951847,3.437573,...,7.769016,8.964655,8.973874,5.470847,7.023548,9.563756,5.953739,4.374953,7.687563,8.691736
GSM2137107,1.995199,3.453598,2.908943,8.919501,4.205525,3.219758,4.841385,5.042885,9.129324,3.927233,...,7.607348,8.747328,8.850202,5.861981,7.032782,10.309471,6.441748,4.434606,7.554528,8.881209
GSM2137108,3.982334,3.869297,2.948449,8.461618,4.468499,4.008897,4.830632,5.670238,8.984328,4.093080,...,8.181692,9.125575,8.873725,5.270558,6.407999,8.712529,6.395317,4.754459,7.727718,8.677669
GSM2137109,1.931912,3.657101,4.390043,8.623355,3.803331,3.329403,4.317178,5.997588,9.332712,4.007213,...,7.820397,9.069256,9.384279,5.380734,6.846073,9.381491,5.983618,4.185220,7.542234,8.736329
GSM2137110,1.437287,3.417540,3.199383,8.748830,2.403188,3.964574,4.415696,5.164858,9.074930,3.446358,...,7.767819,8.805099,9.094576,5.550305,6.500735,9.403628,6.037162,4.378950,7.525630,8.802997

In [25]:
final_df = pd.merge(aux_df, matrix_df, left_index = True, right_index = True)
final_df.dropna(inplace = True)
final_df.to_csv("data/matrix_nasal.csv", header = True, index = True)

final_df.head()

,cancer,age,gender,smoker,smoking_quit,mass_size,7892501,7892502,7892503,7892504,...,8180408,8180409,8180410,8180411,8180413,8180414,8180415,8180416,8180417,8180418
geoid,,,,,,,,,,,,,,,,,,,,,
GSM2137106,1,51,0,1,1,-1,2.288567,3.467242,3.106184,8.791999,...,7.769016,8.964655,8.973874,5.470847,7.023548,9.563756,5.953739,4.374953,7.687563,8.691736
GSM2137107,1,69,0,0,-1,1,1.995199,3.453598,2.908943,8.919501,...,7.607348,8.747328,8.850202,5.861981,7.032782,10.309471,6.441748,4.434606,7.554528,8.881209
GSM2137108,1,58,0,0,1,-1,3.982334,3.869297,2.948449,8.461618,...,8.181692,9.125575,8.873725,5.270558,6.407999,8.712529,6.395317,4.754459,7.727718,8.677669
GSM2137109,0,49,1,1,1,1,1.931912,3.657101,4.390043,8.623355,...,7.820397,9.069256,9.384279,5.380734,6.846073,9.381491,5.983618,4.185220,7.542234,8.736329
GSM2137110,1,45.3123,0,1,1,1,1.437287,3.417540,3.199383,8.748830,...,7.767819,8.805099,9.094576,5.550305,6.500735,9.403628,6.037162,4.378950,7.525630,8.802997

# Map Probe IDs to Genes

Dataset from AffyMetrix' public site

In [7]:
probeSetData = list(csv.reader(open("data/probeset.csv","r"), delimiter=","))
# Chop off the leading annotations
probeSet_df = pd.DataFrame.from_records(probeSetData[22:])
probeSet_df.columns = probeSet_df.iloc[0] # set first row equal to headers
probeSet_df = probeSet_df.reindex(probeSet_df.index.drop(0))
probeSet_df.head()

,probeset_id,seqname,strand,start,stop,probe_count,transcript_cluster_id,exon_id,psr_id,gene_assignment,...,genscan,genscanSubopt,mouse_fl,mouse_mrna,rat_fl,rat_mrna,microRNAregistry,rnaGene,mitomap,probeset_type
1,7896737,chr1,+,54904,54936,7,7896736,96595542,97686464,---,...,0,0,0,0,0,0,0,0,0,main
2,7896739,chr1,+,63033,63649,31,7896738,96595544,97686467,XR_916795 // OR4G2P /// OTTHUMT00000334543 // ...,...,0,0,0,0,0,0,0,0,0,main
3,7896741,chr1,+,69109,70008,24,7896740,96595546,97686470,NM_001004195 // OR4F4 /// ENST00000326183 // O...,...,0,0,0,0,0,0,0,0,0,main
4,7896743,chr1,+,334144,334272,6,7896742,96595548,97686473,---,...,0,0,0,0,0,0,0,0,0,main
5,7896745,chr1,+,367693,368597,36,7896744,96595550,97686476,NM_001005221 // OR4F29 /// NM_001005224 // OR4...,...,0,0,0,0,0,0,0,0,0,main

Create a dictionary that looks up the gene assignment, given an input probeset_id

In [8]:
pid_gene_pairs = probeSet_df.iloc[:,[6,9]].values
gene_dict = {} 
for j in range(pid_gene_pairs.shape[0]):
    pid = pid_gene_pairs[j][0] 
    if (pid_gene_pairs[j][1] != '---'): 
        genes = tuple(set( [s.split('//')[1].strip() for s in pid_gene_pairs[j][1].split('///')] ))
        gene_dict[pid] = genes

In [9]:
f = open("data/gene_dict.pkl",'wb')
pickle.dump(gene_dict,f)
f.close()